version: '3'

services:

  zookeeperA:
    image: confluentinc/cp-zookeeper
    hostname: zookeeperA
    container_name: zookeeperA
    ports:
      - 22181:22181
      - 22888:22888
      - 23888:23888
    volumes:
      - ./zookeeperA/data:/data
    environment:
      ZOOKEEPER_SERVER_ID: 1    
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeperA:22888:23888
      
  broker1A:
    image: confluentinc/cp-kafka
    hostname: broker1A
    container_name: broker1A
    ports:
      - 9092:9092
      - 29092:29092
    depends_on:
      - zookeeperA
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeperA:22181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker1A:29092,PLAINTEXT_HOST://localhost:9092
      ALLOW_PLAINTEXT_LISTENER: 'yes'    
      KAFKA_AUTO_OFFSET_RESET: "latest"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui-1:
    container_name: kafka-ui-1
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080 # Changed to avoid port clash with akhq
    depends_on:
      - broker1A
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker1A:29092
      DYNAMIC_CONFIG_ENABLED: 'true'
  
  zookeeperB:
    image: confluentinc/cp-zookeeper
    hostname: zookeeperB
    container_name: zookeeperB
    ports:
      - 32181:32181
      - 32888:32888
      - 33888:33888
    volumes:
      - ./zookeeperB/data:/data
    environment:
      ZOOKEEPER_SERVER_ID: 1    
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeperB:32888:33888
      
  broker1B:
    image: confluentinc/cp-kafka
    hostname: broker1B
    container_name: broker1B
    ports:
      - 8092:8092
      - 29093:29093
    depends_on:
      - zookeeperB
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeperB:32181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:8092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker1B:29093,PLAINTEXT_HOST://localhost:8092
      ALLOW_PLAINTEXT_LISTENER: 'yes'    
      KAFKA_AUTO_OFFSET_RESET: "latest"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui-2:
    container_name: kafka-ui-2
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8081:8080 # Changed to avoid port clash with akhq
    depends_on:
      - broker1B
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker1B:29093
      DYNAMIC_CONFIG_ENABLED: 'true'    

  zookeeperC:
    image: confluentinc/cp-zookeeper
    hostname: zookeeperC
    container_name: zookeeperC
    ports:
      - 42181:42181
      - 42888:42888
      - 43888:43888
    volumes:
      - ./zookeeperC/data:/data
    environment:
      ZOOKEEPER_SERVER_ID: 1    
      ZOOKEEPER_CLIENT_PORT: 42181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeperB:42888:43888
      
  broker1C:
    image: confluentinc/cp-kafka
    hostname: broker1C
    container_name: broker1C
    ports:
      - 7092:7092
      - 29094:29094
    depends_on:
      - zookeeperC
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeperC:42181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29094,PLAINTEXT_HOST://0.0.0.0:8092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker1C:29094,PLAINTEXT_HOST://localhost:8092
      ALLOW_PLAINTEXT_LISTENER: 'yes'    
      KAFKA_AUTO_OFFSET_RESET: "latest"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui-3:
    container_name: kafka-ui-3
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8083:8080 # Changed to avoid port clash with akhq
    depends_on:
      - broker1C
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker1C:29094
      DYNAMIC_CONFIG_ENABLED: 'true'


  mirror-maker-1:
    image: confluentinc/cp-kafka
    entrypoint: connect-mirror-maker /tmp/kafka/config/mm2.properties
    hostname: mirror-maker-1
    container_name: mirror-maker-1
    volumes:
      - ./mm2_config:/tmp/kafka/config
    ports:
      - 9091:9091
      - 29096:29096
    depends_on:
      - broker1A
      - broker1B
      - broker1C
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:29096,PLAINTEXT_HOST://:9091
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://mirror-maker-1:29096,PLAINTEXT_HOST://localhost:9091
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_AUTO_OFFSET_RESET: "latest"
      KAFKA_LOG4J_OPTS: "-Dlog4j.configuration=file:/etc/kafka/connect-log4j.properties"

  mirror-maker-2:
    image: confluentinc/cp-kafka
    entrypoint: connect-mirror-maker /tmp/kafka/config/mm2.properties
    hostname: mirror-maker-2
    container_name: mirror-maker-2
    volumes:
      - ./mm2_config:/tmp/kafka/config
    ports:
      - 9191:9191
      - 29097:29097
    depends_on:
      - broker1A
      - broker1B
      - broker1C
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:29097,PLAINTEXT_HOST://:9191
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://mirror-maker-2:29097,PLAINTEXT_HOST://localhost:9191
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_AUTO_OFFSET_RESET: "latest"
      KAFKA_LOG4J_OPTS: "-Dlog4j.configuration=file:/etc/kafka/connect-log4j.properties"

  mirror-maker-3:
    image: confluentinc/cp-kafka
    entrypoint: connect-mirror-maker /tmp/kafka/config/mm2.properties
    hostname: mirror-maker-3
    container_name: mirror-maker-3
    volumes:
      - ./mm2_config:/tmp/kafka/config
    ports:
      - 9291:9291
      - 29098:29098
    depends_on:
      - broker1A
      - broker1B
      - broker1C
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:29098,PLAINTEXT_HOST://:9291
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://mirror-maker-3:29098,PLAINTEXT_HOST://localhost:9291
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_AUTO_OFFSET_RESET: "latest"
      KAFKA_LOG4J_OPTS: "-Dlog4j.configuration=file:/etc/kafka/connect-log4j.properties"